# Generated by Django 3.2.20 on 2024-03-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
