# Generated by Django 3.2.20 on 2024-03-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book/image')),
                ('pdf', models.FileField(upload_to='book/pdf')),
            ],
        ),
    ]
